/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRazorpayOrderRouteImport } from './routes/api.razorpay.order'
import { Route as ApiRazorpayVerifyRouteImport } from './routes/api.razorpay.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayOrderRoute = ApiRazorpayOrderRouteImport.update({
  id: '/api/razorpay/order',
  path: '/api/razorpay/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayVerifyRoute = ApiRazorpayVerifyRouteImport.update({
  id: '/api/razorpay/verify',
  path: '/api/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/razorpay/order': typeof ApiRazorpayOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/razorpay/order' | '/api/razorpay/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/razorpay/order' | '/api/razorpay/verify'
  id: '__root__' | '/' | '/api/razorpay/order' | '/api/razorpay/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRazorpayOrderRoute: typeof ApiRazorpayOrderRoute
  ApiRazorpayVerifyRoute: typeof ApiRazorpayVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/order': {
      id: '/api/razorpay/order'
      path: '/api/razorpay/order'
      fullPath: '/api/razorpay/order'
      preLoaderRoute: typeof ApiRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/verify': {
      id: '/api/razorpay/verify'
      path: '/api/razorpay/verify'
      fullPath: '/api/razorpay/verify'
      preLoaderRoute: typeof ApiRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRazorpayOrderRoute: ApiRazorpayOrderRoute,
  ApiRazorpayVerifyRoute: ApiRazorpayVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
